controller_manager:
  ros__parameters:
    update_rate: 250  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      
    joint_traj_compliance_controller:
      type: joint_traj_compliance_controller/JointTrajComplianceController

    forward_command_controller_position:
      type: forward_command_controller/ForwardCommandController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - rob1_joint_1
      - rob1_joint_2
      - rob1_joint_3
      - rob1_joint_4
      - rob1_joint_5
      - rob1_joint_6
      - ext_joint_1
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0

joint_traj_compliance_controller:
  ros__parameters:
    joints:
      - rob1_joint_1
      - rob1_joint_2
      - rob1_joint_3
      - rob1_joint_4
      - rob1_joint_5
      - rob1_joint_6
      - ext_joint_1
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 250.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0
    gains:
      #!!These values have not been optimized!!
      rob1_joint_1: {p: 0.0,  d: 0.0, i: 0.0, i_clamp: 1.0}
      rob1_joint_2: {p: 0.0,  d: 0.0, i: 0.0, i_clamp: 1.0}
      rob1_joint_3: {p: 0.0,  d: 0.0, i: 0.0, i_clamp: 1.0}
      rob1_joint_4: {p: 0.0,  d: 0.0, i: 0.0, i_clamp: 1.0}
      rob1_joint_5: {p: 0.0,  d: 0.0, i: 0.0, i_clamp: 1.0}
      rob1_joint_6: {p: 0.0,  d: 0.0, i: 0.0, i_clamp: 1.0}
      ext_joint_1: {p: 0.0, d: 0.0, i: 0.0, i_clamp: 1.0}
    ff_velocity_scale/rob1_joint_1: 1.0
    ff_velocity_scale/rob1_joint_2: 1.0
    ff_velocity_scale/rob1_joint_3: 1.0
    ff_velocity_scale/rob1_joint_4: 1.0
    ff_velocity_scale/rob1_joint_5: 1.0
    ff_velocity_scale/rob1_joint_6: 1.0
    ff_velocity_scale/ext_joint_1: 1.0    

forward_command_controller_position:
  ros__parameters:
    joints:
      - rob1_joint_1
      - rob1_joint_2
      - rob1_joint_3
      - rob1_joint_4
      - rob1_joint_5
      - rob1_joint_6
      - ext_joint_1
    interface_name: position
