# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  rob1_joint_1:
    has_velocity_limits: true
    max_velocity: 5.027
    has_acceleration_limits: false
    max_acceleration: 0
  rob1_joint_2:
    has_velocity_limits: true
    max_velocity: 4.189
    has_acceleration_limits: false
    max_acceleration: 0
  rob1_joint_3:
    has_velocity_limits: true
    max_velocity: 5.236
    has_acceleration_limits: false
    max_acceleration: 0
  rob1_joint_4:
    has_velocity_limits: true
    max_velocity: 6.981
    has_acceleration_limits: false
    max_acceleration: 0
  rob1_joint_5:
    has_velocity_limits: true
    max_velocity: 7.069
    has_acceleration_limits: false
    max_acceleration: 0
  rob1_joint_6:
    has_velocity_limits: true
    max_velocity: 10.472
    has_acceleration_limits: false
    max_acceleration: 0
  ext_joint_1:
    has_velocity_limits: true
    max_velocity: 10.472
    has_acceleration_limits: false
    max_acceleration: 0
