manipulator:
  #  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  #  kinematics_solver_search_resolution: 0.005
  #  kinematics_solver_timeout: 0.005
  #  kinematics_solver_attempts: 3
  #kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  #kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver: moveit_opw_kinematics_plugin/MoveItOPWKinematicsPlugin
  opw_kinematics_geometric_parameters:
    a1: 0.00
    a2: -0.042
    b: 0.000
    c1: 0.3991
    c2: 0.448
    c3: 0.451
    c4: 0.082
  opw_kinematics_joint_offsets: [ 0.0, 0.0,-1.57079632679, 0, 0, 0 ]
  opw_kinematics_joint_sign_corrections: [ 1, 1, 1, 1, 1, 1 ]
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3

    #kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
    #kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
#    kinematics_solver: moveit_opw_kinematics_plugin/MoveItOPWKinematicsPlugin
#    opw_kinematics_geometric_parameters:
#      a1: 0.00
#      a2: -0.042
#      b: 0.000
#      c1: 0.3991
#      c2: 0.448
#      c3: 0.451
#      c4: 0.082
#    opw_kinematics_joint_offsets: [ 0.0, 0.0,-1.57079632679, 0, 0, 0 ]
#    opw_kinematics_joint_sign_corrections: [ 1, 1, 1, 1, 1, 1 ]
#    kinematics_solver_search_resolution: 0.005
#    kinematics_solver_timeout: 0.005
#    kinematics_solver_attempts: 3